name: Build & Release

on:
  push:
    paths:
      - '.github/workflows/build-release.yml'
      - 'eco-core/**/*'
      - 'gradle/**/*'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle.kts'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        #run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup build cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace
        
      - name: Archive Repository
        run: |
          # Create a zip file of the entire repository contents
          zip -r dev_env.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dev_env-${{ steps.vars.outputs.sha_short }}
          path: dev_env.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: EcoJobs-${{ steps.vars.outputs.sha_short }}
          path: build/libs
      
      - name: Release Files
        uses: softprops/action-gh-release@v1
        with: 
          token: ${{ secrets.RELEASE_KEY }}
          files: |
            build/libs/*.jar
            dev_env.zip
          tag_name: commit-${{ steps.vars.outputs.sha_short }}
          name: EcoJobs ${{ steps.vars.outputs.sha_short }}
          body: |
            Commit ${{ steps.vars.outputs.sha_short }}
            EcoJobs
          generate_release_notes: true
        env:
          GITHUB_REPOSITORY: MediumCraft/EcoJobs
